### ISSUE TITLE
Can't connect after pair on latest combo version

### ISSUE THREAD

**Issue by William1444** [MilosKozak/ruffy#1]
Hi

I just tried to pair using the pair branch, then switched to the latest combo build and unfortunately could not control the pump. I ended up reverting to an older commit to get the combo branch working.

Sorry it is a little garbled. It is very late here

Will

**Comment by pedroll** [comment]
What commit is working for you?

**Comment by jotomo** [comment]
Closing due to unresponsive reporter and not enough information to work with. Re-open if the problem still exists and provide versions / commits used and AndroidAPS logs (see wiki).
