### ISSUE TITLE
Pairing branch not building

### ISSUE THREAD

**Issue by jgslade** [MilosKozak/ruffy#12]
I got a new phone since the old one was randomly dying between 40-60% battery. I paired my combo to the new phone, but AndroidAPS wouldn't start the ruffy service, so I thought I try to repair my combo with the old phone, and it wouldn't pair, so I tried to pair to the new phone again and it wouldn't. I then tried to build the pairing branch to see if I could get the combo to pair again, but I get this error when trying to generate the signed APK:

```
/home/sam/StudioProjects/ruffy/app/src/main/java/org/monkey/d/ruffy/ruffy/driver/Ruffy.java:420: error: <anonymous org.monkey.d.ruffy.ruffy.driver.Ruffy$5> is not abstract and does not override abstract method cmdModeDeactivated() in AppHandler
    private AppHandler rtAppHandler = new AppHandler() {
                                                       ^
```

**Comment by jotomo** [comment]
The message refers to code not present in the `pairing` branch.
Make sure you cloned this repository not the monkey-r one.
