### ISSUE TITLE
Pump unreachable alerts

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/ruffy#15]
From time to time there is a "Pump Unreachable" alarm - this seems to happen when there has been an extended period of TBR = 0

The error can be cleared by pressing any button on the Combo to wake it up and the pump then seems to be reachable again. This problem has occurred using two different (new) pumps and two different phones.

On an previous rig I was using an earlier version of Ruffy "ruffy-jotomo.apk" and the error never occurred once over a priod of several years.

**Comment by jotomo** [comment]
This isn't fixable within a reasonable amount of time.
However, the Combo v2 driver has likely solved this issue (currently in the `dev` branch of AAPS), please try that.
