### ISSUE TITLE
Error while creating the APK

### ISSUE THREAD

**Issue by nitroks14** [MilosKozak/ruffy#5]
![image](https://user-images.githubusercontent.com/43478520/54123336-bdb52e80-43ff-11e9-9a88-d9994e18787b.png)

![image](https://user-images.githubusercontent.com/43478520/54123451-1f759880-4400-11e9-8a1c-215d18056a5e.png)

Idem after 2 rebuild.

**Comment by nitroks14** [comment]
It's ok if I do not upgrade Android Studio to v4.10
![image](https://user-images.githubusercontent.com/43478520/54124537-f571a580-4402-11e9-82a4-f618e3b77449.png)

**Comment by YoloDoge** [comment]
I followed your tip and it helped. I think this issue can be closed ...
