### ISSUE TITLE
Can't pair

### ISSUE THREAD

**Issue by YoloDoge** [MilosKozak/ruffy#6]
@MilosKozak I don't know if I'm right here, but I need some support. After finding my phone at the Spirit Combo, I try to pair. The prompt for entering  the pin appears, but dissappears very fast after that. In that way I am not able to connect the Spirit Combo to Ruffy. Ruffy gives me the understanding errors.

![Screenshot_2019-03-15-18-54-13-064_org monkey d ruffy ruffy](https://user-images.githubusercontent.com/48335829/54459748-ecb50280-4767-11e9-924f-c18da28a0a66.png)

**Comment by zxcz191** [comment]
Hi! Did you solve this problem?

**Comment by YoloDoge** [comment]
No, not yet. I suppose that the phone's firmware is the problem. I  going to install the latest LineageOS and try to install ruffy and try to connect again. I only need to wait until I can unlock the bootloader (it has a time lock)

**Comment by zxcz191** [comment]
Could you please tell me how it ends?))

**Comment by YoloDoge** [comment]
I will

**Comment by YoloDoge** [comment]
@zxcz191 I did it. It took a long time before I was able to unlock the bootloader and install the latest LineageOS. After installing LineageOS, I reinstalled Ruffy (with the master branch) and after some attempts I was able to pair the Spirit Combo with my phone. Now I am running the closed loop, and (oh boy) what a relief!
